version: "3.8"

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/backend  # Mount source code for live reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app  # Mount source code for live reload
      - /app/node_modules  # Prevent overwriting node_modules
    environment:
      - WATCHPACK_POLLING=true  # Enable polling for live reload
